config/routes.rb
Rails.application.routes.draw do
  devise_for :managers
  devise_for :customers

  resources :categories do
    resources :books
  end

  resources :books

  resources :carts do
    collection do
      post 'order'
      get  'thanks'
      get  'create_and'
    end
  end

  root 'categories#index'

  namespace :admin do
    resources :books do
      collection do
        post 'reorder'
      end
      member do
        get 'row'
      end
    end
    resources :categories do
      resources :books
    end
    root to: 'books#index'
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :category

  def self.change_display_order(id, order)
    book = Book.find(id)
    book.display_order = order
    book.save!
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :book
  belongs_to :customer

  validates_presence_of :customer_id, :book_id, :quantity
  validates_numericality_of :quantity, allow_blank: true

  def self.list(customer_id)
    Cart.where(:customer_id => customer_id).order(:created_at)
  end

  def self.total(customer_id)
    self.list(customer_id).inject(0) {|total, cart|  total + cart.book.price * cart.quantity}
  end

  def self.checkout(customer_id)
    Cart.where(:customer_id => customer_id).delete_all
  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/manager.rb
class Manager < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  layout 'admin'

  before_action :authenticate_manager!
  before_action :set_admin_book, only: [:show, :edit, :update, :destroy]

  # GET /admin/books
  def index
    if params[:category_id]
      @books = Book.where(category_id: params[:category_id]).order(:display_order)
    else
      @books = Category.first.books.order(:display_order)
    end
    render layout: 'admin'
  end

  # GET /admin/books/1
  def show
  end

  # GET /admin/books/new
  def new
    @book = Book.new
  end

  # GET /admin/books/1/edit
  def edit
  end

  # POST /admin/books
  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to admin_book_path(@book), notice: '作成しました'
    else
      render action: 'new'
    end
  end
  
  def reorder
    if request.xhr?
      order_infos = params[:order_infos]
      order_id = 1
      order_infos.each do |info|
        if info != ""
          last_index = info.length - 1
          id = info[4..last_index]
          Book.change_display_order(id,order_id)
          order_id += 1
        end
      end
      render :json => {info: "success"}
    end
  end
  # PATCH/PUT /admin/books/1
  def update
    if @book.update(book_params)
      if request.xhr?
        render :json =>{
          id: @book.id,
          isbn: @book.isbn,
          title: @book.title, 
          author: @book.author,
          price: @book.price,
          category_id: @book.category_id,
          description: @book.description
           }
      else
        redirect_to admin_book_path(@book), notice: '更新しました'
      end
    else
      render action: 'edit'
    end
  end

  # DELETE /admin/books/1
  def destroy
    delete_id = @book.id
    @book.destroy
    if request.xhr?
      render :json =>{ delete_id: delete_id }
    else
      redirect_to admin_books_url, notice: '削除しました'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:isbn, :title, :author, :price, :category_id, :icon_path, :picture_path, :description, :display_order)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    if resource.is_a?(Manager)
      admin_books_path
    else
      if session[:cart_entry]
        create_and_carts_path
      else
        categories_path
      end
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:category_id]
      @books = Book.where(category_id: params[:category_id]).order(:display_order)
    else
      @books = Book.order(:display_order).all
    end
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  layout :false
  before_action :authenticate
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  def index
    @carts = Cart.list(current_customer.id)
    @total = Cart.total(current_customer.id)
    #layout lambda{ |c| c.request.xhr? false : 'application'}
      # if request.xhr?
      #  layout = false; 
      # end
  end

  # GET /carts/1
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  def create
    @cart = Cart.new(cart_params)
    @cart.customer_id = current_customer.id

    if @cart.save
      redirect_to carts_path
    else
      render action: 'edit'
    end
  end

  # PATCH/PUT /carts/1
  def update
    if @cart.update(cart_params)
      redirect_to carts_path
    else
      render action: 'edit'
    end
  end

  # DELETE /carts/1
  def destroy
    @cart.destroy
    if request.xml_http_request?
      index
      render action: "index"
    else
      redirect_to carts_path
    end
  end

  def create_and
    if session[:cart_entry]
      cart_params = session[:cart_entry]
      cart_params[:customer_id] = current_customer.id

      cart = Cart.new(cart_params)
      cart.save
      session[:cart_entry] = nil
      flash[:show_cart] = true
    end
    redirect_to carts_path
  end

  def order
    Cart.checkout(current_customer.id)
    redirect_to thanks_carts_path
  end

  def thanks
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cart_params
      params.require(:cart).permit(:book_id, :customer_id, :quantity)
    end

    def authenticate
      session[:cart_entry] = params[:cart]  if !customer_signed_in? && params[:cart]
      authenticate_customer!
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.order(:display_order)
  end
end

app/controllers/customers_controller.rb
class CustomersController < Devise::SessionsController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def yen(n)
    "￥#{number_with_delimiter(n)}"
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/admin/books/_form.html.erb
<%= form_for @book, remote: true, url: @book.id ? admin_book_path(@book) : admin_books_path,
  html: { class: 'form-horizontal form-update', role: 'form' } do |f| %>

    <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= @book.errors.count %>つの入力間違いがあります:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :isbn, class: 'control-label' %>
    <div class="col-lg-10"><%= f.text_field :isbn %></div>
  </div>
  <div class="form-group">
    <%= f.label :title, class: 'control-label' %>
    <div class="col-lg-10"><%= f.text_field :title, size: 60 %></div>
  </div>
  <div class="form-group">
    <%= f.label :author, class: 'control-label' %>
    <div class="col-lg-10"><%= f.text_field :author, size: 60 %></div>
  </div>
  <div class="form-group">
    <%= f.label :price, class: 'control-label' %>
    <div class="col-lg-10"><%= f.number_field :price, size: 60 %></div>
  </div>
  <div class="form-group">
    <%= f.label :category_id, class: 'control-label' %>
    <div class="col-lg-10"><%= f.select :category_id, Category.order(:id).map{|c| [c.name, c.id]}, class: 'form-control' %></div>
  </div>
  <div class="form-group">
    <%= f.label :display_order, class: 'control-label' %>
    <div class="col-lg-10"><%= f.number_field :display_order %></div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'control-label' %>
    <div class="col-lg-10"><%= f.text_area :description, rows: 10, cols: 60 %></div>
  </div>

  <div class="form-group">
    <%= f.submit nil, class: 'btn btn-primary btn-update' %>
    <%= link_to "戻る", admin_books_path, remote: true, class: 'btn btn-default btn-back' %>
  </div>
<% end %>

app/views/admin/books/edit.html.erb
<h1>編集</h1>

<%= render 'form' %>

app/views/admin/books/index.html.erb
<div class="page-header">
  <h1>書籍管理</h1>
</div>

<div class="row">
  <div class="col-md-2">
    <%= select_tag "category_selector", options_for_select(Category.all.map{|c| [c.name, c.id]}, @books.first.category_id), class: 'form-control' %>
  </div>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>タイトル</th>
      <th>著者</th>
      <th>値段</th>
      <th></th>
    </tr>
  </thead>
  <tbody id="sortable">
    <% @books.each do |book| %>
      <tr id="<%= "row_#{book.id}" %>">
        <td><%= image_tag book.icon_path %></td>
        <td class="title"><%= book.title %></td>
        <td class="author"><%= book.author %></td>
        <td class="price"><%= yen book.price %></td>
        <td>
          <% show_btn_id = "show_#{book.id}" %>
          <% edit_btn_id = "edit_#{book.id}" %>
          <%= link_to '詳細', admin_book_path(book), remote: true, class: 'btn btn-sm btn-default btn_show', id: show_btn_id%>
          <%= link_to '編集', edit_admin_book_path(book), remote: true, class: 'btn btn-sm btn-primary btn_edit', id: edit_btn_id  %>
          <%= link_to '削除', admin_book_path(book), remote: true, method: :delete, data: { confirm: "「#{book.title}」を削除しますか?" }, class: 'btn btn-sm btn-danger btn_delete' %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td id="<%= "row_edit" %>" colspan=5>
      </td>
    </tr>
  </tbody>
</table>
<br />
<div id="edit_view">
</div>
<%= link_to '新規作成', new_admin_book_path, class: 'btn btn-default' %>

<%= javascript_tag do -%>
$("#category_selector").change(function() {
  location.href = "<%= admin_category_books_path(9999) %>".replace('9999', $(this).val());
});

$(document).on('ajax:success','.btn_edit, .btn_show',function (event, data, status, xhr){
  var btn = $("#"+event.target.id);
  $("#row_edit").html(data);
  btn.parent().parent().after($("#row_edit").parent());
})

$(document).on('ajax:success','.btn-back',function (event, data, status, xhr){
  $("#row_edit").html("");
})
$(document).on('ajax:success','.btn_show_edit',function (event, data, status, xhr){
  $("#row_edit").html(data);
})

$(document).on('ajax:success','.form-update',function (event, data, status, xhr){
  var edit_item = $("#row_"+data.id);
  edit_item.children(".title").text(data.title);
  edit_item.children(".author").text(data.author);
  edit_item.children(".price").text(toYen(data.price));
  $("#row_edit").html("");
})

$(document).on('ajax:success','.btn_delete',function (event, data, status, xhr){
  $("#row_"+data.delete_id).remove();
})


$(function() {
  $( "#sortable" ).sortable();
  $( "#sortable" ).disableSelection();
});

$( "#sortable" ).sortable ({
  update: function (event, ui ) {
    var serialize_order = $( "#sortable" ).sortable( "toArray" );
    $.post("<%= reorder_admin_books_path %>",{ 'order_infos[]': serialize_order });
  }
});

function toYen(money){
  money_str = String(money);
  if(money < 0){
    money_str = money_str.substring(1,money_str.length);
  }
  var left = money_str.length;
  var str = "";
  while (left > 3){
    str_new = ","+money_str.substring(left-3,left);
    str = str_new.concat(str);
    left -= 3;
  }
  if(money > 0)
    str = ["¥",money_str.substring(0,left),str].join("");
  else
    str = ["¥-",money_str.substring(0,left),str].join("");
  return str;
}

<% end %>

app/views/admin/books/new.html.erb
<h1>新規作成</h1>

<%= render 'form' %>

app/views/admin/books/show.html.erb
<div class="page-header">
  <h1><%= @book.title %></h1>
</div>

<div class="row">
  <div class="span4">
    <%= image_tag @book.picture_path %>
  </div>
  <div class="span5">
    <dl class="dl-horizontal">
      <dt><strong>タイトル</strong></dt>
      <dd><%= @book.title %></dd>
      <dt><strong>著者</strong></dt>
      <dd><%= @book.author %></dd>
      <dt><strong>価格</strong></dt>
      <dd><%= yen @book.price %></dd>
      <dt><strong>カテゴリー</strong></dt>
      <dd><%= @book.category.name %></dd>
      <dt><strong>ISBN</strong></dt>
      <dd><%= @book.isbn %></dd>
      <dt><strong>表示順</strong></dt>
      <dd><%= @book.display_order %></dd>
      <dt><strong>内容</strong></dt>
      <dd><%= @book.description %></dd>
    </dl>
    <div class="form-actions">
      <%= link_to '編集', edit_admin_book_path(@book), class: 'btn btn-primary btn_show_edit', remote: true %>
      <%= link_to '戻る', admin_books_path, class: 'btn btn-default btn-back', remote: true  %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="page-header">
  <h1>書籍 : <%= @books.first.category.name %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>タイトル</th>
      <th>著者</th>
      <th>値段</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to (image_tag book.icon_path), book %></td>
        <td><%= link_to book.title, book %></td>
        <td><%= book.author %></td>
        <td><%= yen book.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<div class="page-header">
  <h1><%= @book.title %></h1>
</div>

<div class="row">
  <div class="col-md-4">
    <%= image_tag @book.picture_path %>
  </div>
  <div class="col-md-5">
    <dl class="dl-horizontal">
      <dt><strong>タイトル</strong></dt>
      <dd><%= @book.title %></dd>
      <dt><strong>著者</strong></dt>
      <dd><%= @book.author %></dd>
      <dt><strong>価格</strong></dt>
      <dd><%= yen @book.price %></dd>
      <dt><strong>カテゴリー</strong></dt>
      <dd><%= @book.category.name %></dd>
      <dt><strong>ISBN</strong></dt>
      <dd><%= @book.isbn %></dd>
      <dt><strong>内容</strong></dt>
      <dd><%= @book.description %></dd>
    </dl>

    <div class="form-actions">
      <%= link_to "戻る", category_books_path(@book.category_id), class: 'btn btn-default'  %>
      <%= link_to "カートに入れる", carts_path(cart: {book_id: @book.id, quantity: 1}),
            method: :post, class: customer_signed_in?  ? 'btn  btn-primary' : 'btn btn-default' %>
    </div>
  </div>
</div>

app/views/carts/_form.html.erb
<%= form_for @cart, remote: true, html: { id: 'cart_form' ,class: 'form-horizontal',  role: 'form' } do |f| %>

  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= @cart.errors.count %>つの入力間違いがあります:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :book_id, class: 'control-label' %>
    <div class="controls">
      <%= @cart.book.title %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :quantity, class: 'control-label' %>
    <div class="controls">
      <%= f.number_field :quantity, class: 'number_field' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.submit nil ,remote: true, class: 'btn btn-primary btn_edit', id: 'submit'%>
    <%= link_to "戻る", carts_path, remote: true,class: 'btn btn-default', id: 'form_cancel' %>
  </div>
<% end %>

app/views/carts/_index.html.erb
<div class="page-header">
  <h1>ショッピングカート</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th colspan="2">書籍</th>
      <th>価格</th>
      <th>数量</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= image_tag cart.book.icon_path %></td>
        <td><%= cart.book.title %></td>
        <td><%= yen cart.book.price %></td>
        <td><%= cart.quantity %></td>
        <td>
          <%= link_to "数量変更", edit_cart_path(cart), remote: true, id: "cart_num_change", "data-target" => "#cart_num", class: 'btn btn-sm btn-default' %>
          <%= link_to "削除", cart, method: :delete, 
                data: { confirm: '削除しますか?' }, class: 'btn btn-sm btn-danger' %>
         </td>
      </tr>
    <% end %>
      <tr>
        <th colspan="4">合計</th>
        <td colspan="1"><%= yen @total%></td>
      </tr>  
  </tbody>
</table>

<div class="row">
  <div class="col-md-4 col-md-offset-8">
    <%= link_to '購入', order_carts_path, method: :post, class: 'btn btn-lg btn-primary' %>
    <%= link_to '戻る', root_path, class: 'btn btn-lg btn-default' %>
  </div>
</div>

app/views/carts/edit.html.erb
<div class="page-header">
  <h1>数量変更</h1>
</div>
<%= render 'form' %>

app/views/carts/index.html.erb
<div class="page-header">
  <h1>ショッピングカート</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th colspan="2">書籍</th>
      <th>価格</th>
      <th>数量</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= image_tag cart.book.icon_path %></td>
        <td><%= cart.book.title %></td>
        <td><%= yen cart.book.price %></td>
        <td><%= cart.quantity %></td>
        <td>
          <%= link_to "数量変更", edit_cart_path(cart), class: 'btn btn-sm btn-default' %>
          <%= link_to "削除", cart, method: :delete, 
                data: { confirm: '削除しますか?' }, class: 'btn btn-sm btn-danger' %>
         </td>
      </tr>
    <% end %>
      <tr>
        <th colspan="4">合計</th>
        <td colspan="1"><%= yen @total%></td>
      </tr>  
  </tbody>
</table>

<div class="row">
  <div class="col-md-4 col-md-offset-8">
    <%= link_to '購入', order_carts_path, method: :post, class: 'btn btn-lg btn-primary' %>
    <%= link_to '戻る', root_path, class: 'btn btn-lg btn-default' %>
  </div>
</div>

app/views/carts/thanks.html.erb
<div class="row">
  <div class="span6 offset3">
    <div style="height:80px">&nbsp;</div>
    <h1>お買い上げありがとうございます。</h1>
  </div>
</div>

app/views/categories/index.html.erb
<div class="page-header">
  <h1>カテゴリー</h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>カテゴリー</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.name, category_books_path(category.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/customers/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/admin.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BookStore Admin" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <%= link_to "BookStore Admin", admin_books_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse navbar-ex4-collapse" >
            <p class="navbar-text pull-right">
            <strong><%= manager_signed_in? ? current_manager.name : "" %></strong>
            <% if manager_signed_in? %>
            <%= link_to "ログアウト", destroy_manager_session_path, method: :delete, class: 'navbar-link' %>
            <% else %>
            <%= link_to "ログイン", new_manager_session_path, class: 'navbar-link' %>
            <% end %>
          </p>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="col-md-12">
              <% flash.each do |name, msg| %>
                <% if msg.is_a?(String) %>
                  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                    <a class="close" data-dismiss="alert">&#215;</a>
                    <%= content_tag :div, msg, id: "flash_#{name}" %>
                  </div>
                <% end %>
              <% end %>

              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookStore</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <%= link_to "BookStore", root_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse navbar-ex4-collapse" >
            <p class="navbar-text pull-right">
            <strong><%= customer_signed_in? ? current_customer.name + " 様" : "" %></strong>
            <% if customer_signed_in? %>
            <%= link_to "カート表示", carts_path, remote: true, "data-toggle" => "modal", "data-target" => "#show_cart", id: "cart_button", class: 'navbar-link' %>
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'navbar-link' %>
            <% else %>
            <%= link_to "ログイン", new_customer_session_path, class: 'navbar-link' %>
            <% end %>
          </p>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <% flash.each do |name, msg| %>
                <% if msg.is_a?(String) %>
                  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                    <a class="close" data-dismiss="alert">&#215;</a>
                    <%= content_tag :div, msg, id: "flash_#{name}" %>
                  </div>
                <% end %>
              <% end %>

              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </div>

<div class="modal fade" id="show_cart">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <div id="cart_content">
        </div>
      </div>
    </div>
  </div>


    </div>
  </body>
    <%= javascript_tag do %>
    $("#show_cart").on('load',function (event, data, status, xhr) {
      $("#cart_button").trigger('click');
     })
    $("#cart_button").on('ajax:success',function (event, data, status, xhr) {
    $("#cart_content").html(data);
  })

    $(document).on('ajax:success',"#cart_num_change",function (event, data, status, xhr) {
      $("#cart_content").html(data);  
     })
    $(document).on('ajax:success',"#cart_form",function (event, data, status, xhr) {
      $("#cart_content").html(data);  
     })
    $(document).on('ajax:success',"#form_cancel #form_cancel",function (event, data, status, xhr) {
      $("#cart_content").html(data);  
     })

    <% end %>

</html>